name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-and-format:
    runs-on: docker
    container:
      image: cimg/rust:1.98-node

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run format check
        run: cargo fmt --check

      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y clang libdbus-1-dev libpipewire-0.3-dev libinput-dev libxkbcommon-dev

      - name: Build linux
        run: cargo build --target x86_64-unknown-linux-gnu

      - name: Build windows
        run: cargo build --target x86_64-pc-windows-gnu

      - name: Run Clippy linux
        run: cargo clippy --target x86_64-unknown-linux-gnu

      - name: Run Clippy windows
        run: cargo clippy --target x86_64-pc-windows-gnu
