name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-and-format:
    runs-on: docker
    container:
      image: node

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v2
        with:
          cache: false
          target: x86_64-pc-windows-gnu
          components: rustfmt, clippy

      - name: Run format check
        run: cargo fmt --check

      - name: Install dependencies
        run: |
          apt-get update &&
          apt-get install -y  \
          libwayland-dev libpipewire-0.3-dev clang libudev-dev libegl1-mesa-dev libinput-dev libxkbcommon-dev libgbm-dev

      - name: Build linux
        run: cargo build --target x86_64-unknown-linux-gnu

      - name: Build windows
        run: cargo build --target x86_64-pc-windows-gnu

      - name: Run Clippy linux
        run: cargo clippy --target x86_64-unknown-linux-gnu

      - name: Run Clippy windows
        run: cargo clippy --target x86_64-pc-windows-gnu
